plugins {
    id 'java-library'
    id 'org.jetbrains.kotlin.jvm'
}

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

dependencies {
    implementation 'javax.inject:javax.inject:1'
    implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-android:1.8.0'

    api "com.jakewharton.threetenabp:threetenabp:1.4.4"
    implementation("io.github.microutils:kotlin-logging:3.0.5")
    implementation("org.slf4j:slf4j-simple:2.0.7")

    testImplementation 'junit:junit:4.13.2'
    testImplementation 'org.junit.jupiter:junit-jupiter:5.10.2'
    testImplementation 'org.threeten:threetenbp:1.6.8'
    testImplementation("org.threeten:threetenbp:1.6.8") {
        exclude module: "com.jakewharton.threetenabp:threetenabp:1.6.8"
    }
}
