plugins {
    id 'java-library'
    id 'org.jetbrains.kotlin.jvm'
}

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

dependencies {
    implementation 'javax.inject:javax.inject:1'
    implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-android:1.8.0'
    testImplementation 'junit:junit:4.13.2'
    testImplementation 'org.junit.jupiter:junit-jupiter:5.10.2'
    api "com.jakewharton.threetenabp:threetenabp:1.4.4"
}